### ISSUE TITLE
voting authority fatal error: fault segmentation violation

### ISSUE THREAD

**Issue by mixmasala** [katzenpost/authority#41]
```
13:00:00.015 DEBU state: authority: Wakeup due to voting schedule.
13:00:00.031 DEBU state: Voting for epoch 3940
13:00:00.052 DEBU state: Generating mix topology.
unexpected fault address 0x7fd6f092b55c
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7fd6f092b55c pc=0x5fd354]

goroutine 5 [running]:
runtime.throw(0xd1235a, 0x5)
        /usr/lib/go-1.10/src/runtime/panic.go:616 +0x81 fp=0xc4201fe7d8 sp=0xc4201fe7b8 pc=0x454211
runtime.sigpanic()
        /usr/lib/go-1.10/src/runtime/signal_unix.go:395 +0x211 fp=0xc4201fe828 sp=0xc4201fe7d8 pc=0x46b141
encoding/base64.(*Encoding).Encode(0xc4200d6000, 0xc420116401, 0x3ed, 0x3ed, 0x7fd6f092b55c, 0x2ef, 0x2ef)
        /usr/lib/go-1.10/src/encoding/base64/base64.go:131 +0x174 fp=0xc4201fe890 sp=0xc4201fe828 pc=0x5fd354
github.com/ugorji/go/codec.(*jsonEncDriver).EncodeStringBytes(0xc420466000, 0xc25400, 0x7fd6f092b55c, 0x2ef, 0x2ef)
        /home/user/go/src/github.com/ugorji/go/codec/json.go:484 +0x367 fp=0xc4201fe948 sp=0xc4201fe890 pc=0xaecb07
github.com/ugorji/go/codec.(*jsonEncDriverGenericImpl).EncodeStringBytes(0xc420466000, 0xc4201f9300, 0x7fd6f092b55c, 0x2ef, 0x2ef)
        <autogenerated>:1 +0x6b fp=0xc4201fe980 sp=0xc4201fe948 pc=0xaf79fb
github.com/ugorji/go/codec.(*Encoder).kSlice(0xc4203c6100, 0xc42019e280, 0xc1ef80, 0xc4201f9320, 0x197)
        /home/user/go/src/github.com/ugorji/go/codec/encode.go:328 +0x1786 fp=0xc4201fece8 sp=0xc4201fe980 pc=0x933f66
github.com/ugorji/go/codec.(*Encoder).encodeValue(0xc4203c6100, 0xc1ef80, 0xc4201f9320, 0x197, 0xc42019e280, 0xc4201f9301)
        /home/user/go/src/github.com/ugorji/go/codec/encode.go:1411 +0x494 fp=0xc4201fedd0 sp=0xc4201fece8 pc=0x93c384
github.com/ugorji/go/codec.(*Encoder).kSlice(0xc4203c6100, 0xc42019e240, 0xc1b900, 0xc42009e708, 0x197)
        /home/user/go/src/github.com/ugorji/go/codec/encode.go:475 +0x3e5 fp=0xc4201ff138 sp=0xc4201fedd0 pc=0x932bc5
github.com/ugorji/go/codec.(*Encoder).encodeValue(0xc4203c6100, 0xc1b900, 0xc42009e708, 0x197, 0xc42019e240, 0x484f01)
        /home/user/go/src/github.com/ugorji/go/codec/encode.go:1411 +0x494 fp=0xc4201ff220 sp=0xc4201ff138 pc=0x93c384
github.com/ugorji/go/codec.(*Encoder).kStructNoOmitempty(0xc4203c6100, 0xc42019e180, 0xcff120, 0xc42009e680, 0x199)
        /home/user/go/src/github.com/ugorji/go/codec/encode.go:505 +0x44a fp=0xc4201ff3c8 sp=0xc4201ff220 pc=0x93444a
github.com/ugorji/go/codec.(*Encoder).encodeValue(0xc4203c6100, 0xc01b00, 0xc42009e680, 0x16, 0xc42019e180, 0x401)
        /home/user/go/src/github.com/ugorji/go/codec/encode.go:1411 +0x494 fp=0xc4201ff4b0 sp=0xc4201ff3c8 pc=0x93c384
github.com/ugorji/go/codec.(*Encoder).encode(0xc4203c6100, 0xc01b00, 0xc42009e680)
        /home/user/go/src/github.com/ugorji/go/codec/encode.go:1348 +0x1be fp=0xc4201ff618 sp=0xc4201ff4b0 pc=0x93a99e
github.com/ugorji/go/codec.(*Encoder).MustEncode(0xc4203c6100, 0xc01b00, 0xc42009e680)
        /home/user/go/src/github.com/ugorji/go/codec/encode.go:1232 +0x75 fp=0xc4201ff658 sp=0xc4201ff618 pc=0x93a615
github.com/ugorji/go/codec.(*Encoder).Encode(0xc4203c6100, 0xc01b00, 0xc42009e680, 0xc4203c6100, 0x0)
        /home/user/go/src/github.com/ugorji/go/codec/encode.go:1222 +0xa2 fp=0xc4201ff690 sp=0xc4201ff658 pc=0x93a522
github.com/katzenpost/authority/voting/internal/s11n.SignDocument(0xe0daa0, 0xc420072540, 0xc42009e680, 0x3, 0x3, 0x1, 0x1, 0x3)
        /home/user/go/src/github.com/katzenpost/authority/voting/internal/s11n/document.go:97 +0x123 fp=0xc4201ff758 sp=0xc4201ff690 pc=0xb0c3c3
github.com/katzenpost/authority/voting/server.(*state).sign(0xc4201ae680, 0xc42009e680, 0x4)
        /home/user/go/src/github.com/katzenpost/authority/voting/server/state.go:475 +0xa8 fp=0xc4201ff840 sp=0xc4201ff758 pc=0xbaca18
github.com/katzenpost/authority/voting/server.(*state).vote(0xc4201ae680, 0xf64)
        /home/user/go/src/github.com/katzenpost/authority/voting/server/state.go:450 +0xa4a fp=0xc4201ffd18 sp=0xc4201ff840 pc=0xbac07a
github.com/katzenpost/authority/voting/server.(*state).fsm(0xc4201ae680)
        /home/user/go/src/github.com/katzenpost/authority/voting/server/state.go:197 +0x1903 fp=0xc4201ffeb8 sp=0xc4201ffd18 pc=0xba8d53
github.com/katzenpost/authority/voting/server.(*state).worker(0xc4201ae680)
        /home/user/go/src/github.com/katzenpost/authority/voting/server/state.go:137 +0xa3 fp=0xc4201fff88 sp=0xc4201ffeb8 pc=0xba6303
github.com/katzenpost/authority/voting/server.(*state).(github.com/katzenpost/authority/voting/server.worker)-fm()
        /home/user/go/src/github.com/katzenpost/authority/voting/server/state.go:1475 +0x42 fp=0xc4201fffa8 sp=0xc4201fff88 pc=0xbc0db2
github.com/katzenpost/core/worker.(*Worker).Go.func1(0xc4201ae698, 0xc42022a9f0)
        /home/user/go/src/github.com/katzenpost/core/worker/worker.go:38 +0x5d fp=0xc4201fffd0 sp=0xc4201fffa8 pc=0xba260d
runtime.goexit()
        /usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4201fffd8 sp=0xc4201fffd0 pc=0x483e11
created by github.com/katzenpost/core/worker.(*Worker).Go
        /home/user/go/src/github.com/katzenpost/core/worker/worker.go:36 +0xc5

goroutine 1 [chan receive, 459 minutes]:
github.com/katzenpost/authority/voting/server.(*Server).Wait(...)
        /home/user/go/src/github.com/katzenpost/authority/voting/server/server.go:119
main.main()
        /home/user/go/src/github.com/katzenpost/daemons/authority/voting/main.go:75 +0x4a6

goroutine 20 [syscall, 459 minutes]:
os/signal.signal_recv(0x483e11)
        /usr/lib/go-1.10/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
        /usr/lib/go-1.10/src/os/signal/signal_unix.go:22 +0x30
created by os/signal.init.0
        /usr/lib/go-1.10/src/os/signal/signal_unix.go:28 +0x4f

goroutine 4 [chan receive, 459 minutes]:
github.com/katzenpost/authority/voting/server.New.func2(0xc4201a8500)
        /home/user/go/src/github.com/katzenpost/authority/voting/server/server.go:241 +0x65
created by github.com/katzenpost/authority/voting/server.New
        /home/user/go/src/github.com/katzenpost/authority/voting/server/server.go:240 +0x742

goroutine 3 [select, 459 minutes, locked to thread]:
runtime.gopark(0xd36620, 0x0, 0xd13525, 0x6, 0x18, 0x1)
        /usr/lib/go-1.10/src/runtime/proc.go:291 +0xf9
runtime.selectgo(0xc420050f50, 0xc42002a240)
        /usr/lib/go-1.10/src/runtime/select.go:392 +0x11d4
runtime.ensureSigM.func1()
        /usr/lib/go-1.10/src/runtime/signal_unix.go:549 +0x19f
runtime.goexit()
        /usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1

goroutine 6 [IO wait]:
internal/poll.runtime_pollWait(0x7fd6f1ad9f00, 0x72, 0xc4201b7d10)
        /usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x5e
internal/poll.(*pollDesc).wait(0xc420242018, 0x72, 0xc420240400, 0x0, 0x0)
        /usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0xe5
internal/poll.(*pollDesc).waitRead(0xc420242018, 0xffffffffffffff00, 0x0, 0x0)
        /usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x4b
internal/poll.(*FD).Accept(0xc420242000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/internal/poll/fd_unix.go:372 +0x2e2
net.(*netFD).accept(0xc420242000, 0x402420, 0x7fd6e4021838, 0x0)
        /usr/lib/go-1.10/src/net/fd_unix.go:238 +0x53
net.(*TCPListener).accept(0xc42000fde8, 0xe0a3a0, 0xc42022a480, 0xc420022ec0)
        /usr/lib/go-1.10/src/net/tcpsock_posix.go:136 +0x4e
net.(*TCPListener).Accept(0xc42000fde8, 0xe10820, 0xc4200a80f0, 0x0, 0x0)
        /usr/lib/go-1.10/src/net/tcpsock.go:259 +0x50
github.com/katzenpost/authority/voting/server.(*Server).listenWorker(0xc4201a8500, 0xe0dae0, 0xc42000fde8)
        /home/user/go/src/github.com/katzenpost/authority/voting/server/server.go:136 +0x1a2
created by github.com/katzenpost/authority/voting/server.New
        /home/user/go/src/github.com/katzenpost/authority/voting/server/server.go:263 +0xbe2

goroutine 7 [chan receive, 459 minutes]:
main.main.func1(0xc42002a180, 0xc4201a8500)
        /home/user/go/src/github.com/katzenpost/daemons/authority/voting/main.go:64 +0x42
created by main.main
        /home/user/go/src/github.com/katzenpost/daemons/authority/voting/main.go:63 +0x44d

goroutine 8 [chan receive, 459 minutes]:
        /home/user/go/src/github.com/katzenpost/daemons/authority/voting/main.go:70 +0x42
created by main.main
        /home/user/go/src/github.com/katzenpost/daemons/authority/voting/main.go:69 +0x479
unexpected fault address 0x7f4c8cb0055c
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x1 addr=0x7f4c8cb0055c pc=0x5fd354]

goroutine 35 [running]:
runtime.throw(0xd1235a, 0x5)
        /usr/lib/go-1.10/src/runtime/panic.go:616 +0x81 fp=0xc4200667d8 sp=0xc4200667b8 pc=0x454211
runtime.sigpanic()
        /usr/lib/go-1.10/src/runtime/signal_unix.go:395 +0x211 fp=0xc420066828 sp=0xc4200667d8 pc=0x46b141
encoding/base64.(*Encoding).Encode(0xc4200d6000, 0xc420116401, 0x3ed, 0x3ed, 0x7f4c8cb0055c, 0x2ef, 0x2ef)
        /usr/lib/go-1.10/src/encoding/base64/base64.go:131 +0x174 fp=0xc420066890 sp=0xc420066828 pc=0x5fd354
github.com/ugorji/go/codec.(*jsonEncDriver).EncodeStringBytes(0xc4203a0000, 0xc25400, 0x7f4c8cb0055c, 0x2ef, 0x2ef)
        /home/user/go/src/github.com/ugorji/go/codec/json.go:484 +0x367 fp=0xc420066948 sp=0xc420066890 pc=0xaecb07
github.com/ugorji/go/codec.(*jsonEncDriverGenericImpl).EncodeStringBytes(0xc4203a0000, 0xc4200b4000, 0x7f4c8cb0055c, 0x2ef, 0x2ef)
        <autogenerated>:1 +0x6b fp=0xc420066980 sp=0xc420066948 pc=0xaf79fb
github.com/ugorji/go/codec.(*Encoder).kSlice(0xc4200ee400, 0xc4200ad4c0, 0xc1ef80, 0xc4200b4060, 0x197)
        /home/user/go/src/github.com/ugorji/go/codec/encode.go:328 +0x1786 fp=0xc420066ce8 sp=0xc420066980 pc=0x933f66
github.com/ugorji/go/codec.(*Encoder).encodeValue(0xc4200ee400, 0xc1ef80, 0xc4200b4060, 0x197, 0xc4200ad4c0, 0xc4200b4001)
        /home/user/go/src/github.com/ugorji/go/codec/encode.go:1411 +0x494 fp=0xc420066dd0 sp=0xc420066ce8 pc=0x93c384
github.com/ugorji/go/codec.(*Encoder).kSlice(0xc4200ee400, 0xc4200ad400, 0xc1b900, 0xc42009e638, 0x197)
        /home/user/go/src/github.com/ugorji/go/codec/encode.go:475 +0x3e5 fp=0xc420067138 sp=0xc420066dd0 pc=0x932bc5
github.com/ugorji/go/codec.(*Encoder).encodeValue(0xc4200ee400, 0xc1b900, 0xc42009e638, 0x197, 0xc4200ad400, 0x484f01)
        /home/user/go/src/github.com/ugorji/go/codec/encode.go:1411 +0x494 fp=0xc420067220 sp=0xc420067138 pc=0x93c384
github.com/ugorji/go/codec.(*Encoder).kStructNoOmitempty(0xc4200ee400, 0xc4200ac5c0, 0xcff120, 0xc42009e5b0, 0x199)
        /home/user/go/src/github.com/ugorji/go/codec/encode.go:505 +0x44a fp=0xc4200673c8 sp=0xc420067220 pc=0x93444a
github.com/ugorji/go/codec.(*Encoder).encodeValue(0xc4200ee400, 0xc01b00, 0xc42009e5b0, 0x16, 0xc4200ac5c0, 0x401)
        /home/user/go/src/github.com/ugorji/go/codec/encode.go:1411 +0x494 fp=0xc4200674b0 sp=0xc4200673c8 pc=0x93c384
github.com/ugorji/go/codec.(*Encoder).encode(0xc4200ee400, 0xc01b00, 0xc42009e5b0)
        /home/user/go/src/github.com/ugorji/go/codec/encode.go:1348 +0x1be fp=0xc420067618 sp=0xc4200674b0 pc=0x93a99e
github.com/ugorji/go/codec.(*Encoder).MustEncode(0xc4200ee400, 0xc01b00, 0xc42009e5b0)
        /home/user/go/src/github.com/ugorji/go/codec/encode.go:1232 +0x75 fp=0xc420067658 sp=0xc420067618 pc=0x93a615
github.com/ugorji/go/codec.(*Encoder).Encode(0xc4200ee400, 0xc01b00, 0xc42009e5b0, 0xc4200ee400, 0x0)
        /home/user/go/src/github.com/ugorji/go/codec/encode.go:1222 +0xa2 fp=0xc420067690 sp=0xc420067658 pc=0x93a522
github.com/katzenpost/authority/voting/internal/s11n.SignDocument(0xe0daa0, 0xc4201ca100, 0xc42009e5b0, 0x3, 0x3, 0x1, 0x1, 0x3)
        /home/user/go/src/github.com/katzenpost/authority/voting/internal/s11n/document.go:97 +0x123 fp=0xc420067758 sp=0xc420067690 pc=0xb0c3c3
github.com/katzenpost/authority/voting/server.(*state).sign(0xc4201b2270, 0xc42009e5b0, 0x4)
        /home/user/go/src/github.com/katzenpost/authority/voting/server/state.go:475 +0xa8 fp=0xc420067840 sp=0xc420067758 pc=0xbaca18
github.com/katzenpost/authority/voting/server.(*state).vote(0xc4201b2270, 0xf64)
        /home/user/go/src/github.com/katzenpost/authority/voting/server/state.go:450 +0xa4a fp=0xc420067d18 sp=0xc420067840 pc=0xbac07a
github.com/katzenpost/authority/voting/server.(*state).fsm(0xc4201b2270)
        /home/user/go/src/github.com/katzenpost/authority/voting/server/state.go:197 +0x1903 fp=0xc420067eb8 sp=0xc420067d18 pc=0xba8d53
github.com/katzenpost/authority/voting/server.(*state).worker(0xc4201b2270)
        /home/user/go/src/github.com/katzenpost/authority/voting/server/state.go:137 +0xa3 fp=0xc420067f88 sp=0xc420067eb8 pc=0xba6303
github.com/katzenpost/authority/voting/server.(*state).(github.com/katzenpost/authority/voting/server.worker)-fm()
        /home/user/go/src/github.com/katzenpost/authority/voting/server/state.go:1475 +0x42 fp=0xc420067fa8 sp=0xc420067f88 pc=0xbc0db2
github.com/katzenpost/core/worker.(*Worker).Go.func1(0xc4201b2288, 0xc42022b370)
        /home/user/go/src/github.com/katzenpost/core/worker/worker.go:38 +0x5d fp=0xc420067fd0 sp=0xc420067fa8 pc=0xba260d
runtime.goexit()
        /usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420067fd8 sp=0xc420067fd0 pc=0x483e11
created by github.com/katzenpost/core/worker.(*Worker).Go
        /home/user/go/src/github.com/katzenpost/core/worker/worker.go:36 +0xc5

goroutine 1 [chan receive, 459 minutes]:
github.com/katzenpost/authority/voting/server.(*Server).Wait(...)
        /home/user/go/src/github.com/katzenpost/authority/voting/server/server.go:119
main.main()
        /home/user/go/src/github.com/katzenpost/daemons/authority/voting/main.go:75 +0x4a6

goroutine 20 [syscall, 459 minutes]:
os/signal.signal_recv(0x483e11)
        /usr/lib/go-1.10/src/runtime/sigqueue.go:139 +0xa6
os/signal.loop()
        /usr/lib/go-1.10/src/os/signal/signal_unix.go:22 +0x30
created by os/signal.init.0
        /usr/lib/go-1.10/src/os/signal/signal_unix.go:28 +0x4f

goroutine 22 [select, 459 minutes, locked to thread]:
runtime.gopark(0xd36620, 0x0, 0xd13525, 0x6, 0x18, 0x1)
        /usr/lib/go-1.10/src/runtime/proc.go:291 +0xf9
runtime.selectgo(0xc420055f50, 0xc42008e300)
        /usr/lib/go-1.10/src/runtime/select.go:392 +0x11d4
runtime.ensureSigM.func1()
        /usr/lib/go-1.10/src/runtime/signal_unix.go:549 +0x19f
runtime.goexit()
        /usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1

goroutine 34 [chan receive, 459 minutes]:
github.com/katzenpost/authority/voting/server.New.func2(0xc4201b0000)
        /home/user/go/src/github.com/katzenpost/authority/voting/server/server.go:241 +0x65
created by github.com/katzenpost/authority/voting/server.New
        /home/user/go/src/github.com/katzenpost/authority/voting/server/server.go:240 +0x742

goroutine 36 [IO wait, 119 minutes]:
internal/poll.runtime_pollWait(0x7f4c8d4adf00, 0x72, 0xc42025bd10)
        /usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x5e
internal/poll.(*pollDesc).wait(0xc4201b1998, 0x72, 0xc420073d00, 0x0, 0x0)
        /usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0xe5
internal/poll.(*pollDesc).waitRead(0xc4201b1998, 0xffffffffffffff00, 0x0, 0x0)
        /usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x4b
internal/poll.(*FD).Accept(0xc4201b1980, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/lib/go-1.10/src/internal/poll/fd_unix.go:372 +0x2e2
net.(*netFD).accept(0xc4201b1980, 0x402420, 0x7f4c84021738, 0x0)
        /usr/lib/go-1.10/src/net/fd_unix.go:238 +0x53
net.(*TCPListener).accept(0xc4201bbe50, 0xe0a3a0, 0xc42041ac90, 0xc4201d2100)
        /usr/lib/go-1.10/src/net/tcpsock_posix.go:136 +0x4e
net.(*TCPListener).Accept(0xc4201bbe50, 0xe10820, 0xc42030b9f8, 0x0, 0x0)
        /usr/lib/go-1.10/src/net/tcpsock.go:259 +0x50
github.com/katzenpost/authority/voting/server.(*Server).listenWorker(0xc4201b0000, 0xe0dae0, 0xc4201bbe50)
        /home/user/go/src/github.com/katzenpost/authority/voting/server/server.go:136 +0x1a2
created by github.com/katzenpost/authority/voting/server.New
        /home/user/go/src/github.com/katzenpost/authority/voting/server/server.go:263 +0xbe2

goroutine 37 [chan receive, 459 minutes]:
main.main.func1(0xc42008e240, 0xc4201b0000)
        /home/user/go/src/github.com/katzenpost/daemons/authority/voting/main.go:64 +0x42
created by main.main
        /home/user/go/src/github.com/katzenpost/daemons/authority/voting/main.go:63 +0x44d

goroutine 38 [chan receive, 459 minutes]:
main.main.func2(0xc4201ac000, 0xc4201b0000)
        /home/user/go/src/github.com/katzenpost/daemons/authority/voting/main.go:70 +0x42
created by main.main
        /home/user/go/src/github.com/katzenpost/daemons/authority/voting/main.go:69 +0x479
13:00:00.238 NOTI state: Sending Document for epoch 3940, to all Directory Authorities.
13:00:00.242 DEBU state: authority: FSM in state accept_vote
13:07:30.132 DEBU state: authority: Wakeup due to voting schedule.
13:07:30.132 DEBU state: authority: FSM in state accept_reveal
```

**Comment by mixmasala** [comment]
I haven't seen this issue reoccur and the code has been refactored quite a bit, so I'm going to close this issue.
